### ISSUE TITLE
Thermometers lose shine when hidden

### ISSUE THREAD

**Issue by benaiahpitts** [wmbeers/ga-tia#14]
The bottom of the thermometers lose the shine effect when the div they are in is hidden. Restoring the filter removed from the SVG file earlier does not fix this. It also doesn't seem to affect the first thermometer in the HTML.

![temp](https://cloud.githubusercontent.com/assets/8114035/9420602/6e2434c0-4835-11e5-9f8a-11e473955c8a.png)

**Comment by wmbeers** [comment]
How about we don't hide them, but use JavaScript to update just one thermometer, which changes depending in which region is selected?
On Aug 21, 2015 6:51 PM, benaiahpitts <notifications@github.com> wrote:The bottom of the thermometers lose the shine effect when the div they are in is hidden. Restoring the filter removed from the SVG file earlier does not fix this. It also doesn't seem to affect the first thermometer in the HTML.
