### ISSUE TITLE
Google font missing letters or not appearing at all

### ISSUE THREAD

**Issue by wmbeers** [wmbeers/ga-tia#29]
Talked to Shrujal, clarified that in Chrome, nothing appears at all, which lends more evidence that this is a proxy server issue (see https://developers.google.com/fonts/docs/troubleshooting). The missing "T" etc. is happening in IE7.

**Comment by wmbeers** [comment]
I suggest we confirm whether this is a Proxy/CORS issue as described in Google's troubleshooting, and if so we'll probably have to use a different font. There doesn't seem to be anything we can do (outside of getting GA DOT to not strip the header).

**Comment by benaiahpitts** [comment]
I've changed the font back to Arial so they can check the other fixes (Karen said it was hampering her ability to check the site.) Leaving this open since we don't have confirmation yet.
