### ISSUE TITLE
Rendering issues on narrow screens.

### ISSUE THREAD

**Issue by wmbeers** [wmbeers/ga-tia#8]
The text above the thermometer can overlap the text hovering over the map on the home page if the screen is narrow.
![narrow-screen](https://cloud.githubusercontent.com/assets/379889/9340418/94b261d6-45bd-11e5-8bbd-0c9e50062117.png)

**Comment by benaiahpitts** [comment]
Still need to deal with the Facebook widget in the sidebar, which does not resize with the width of the column.

**Comment by benaiahpitts** [comment]
The Facebook widget width is set when the page loads and is smaller when loaded in a smaller window. Closing.
